#rem.....................Animation 1
MENUID     : 10001
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 2
MENUID     : 10002
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 3
MENUID     : 10003
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 4
MENUID     : 10004
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 5
MENUID     : 10005
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 6
MENUID     : 10006
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 7
MENUID     : 10007
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 8
MENUID     : 10008
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 9
MENUID     : 10009
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation 10
MENUID     : 10010
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 1
MENUID     : 10101
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 2
MENUID     : 10102
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 3
MENUID     : 10103
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 4
MENUID     : 10104
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 5
MENUID     : 10105
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 6
MENUID     : 10106
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 7
MENUID     : 10107
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 8
MENUID     : 10108
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 9
MENUID     : 10109
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered 10
MENUID     : 10110
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 1
MENUID     : 10201
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus  2
MENUID     : 10202
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 3
MENUID     : 10203
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 4
MENUID     : 10204
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 5
MENUID     : 10205
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 6
MENUID     : 10206
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 7
MENUID     : 10207
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 8
MENUID     : 10208
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 9
MENUID     : 10209
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
#rem.....................Animation Layered NoFocus 10
MENUID     : 10210
MENUTYPE   : 10
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :Testing Erase on the fly animations.
#REM>>>>>>>>>>>>>>>>>>>>ANIMATED 
#REM  This is a pause animation. it will play # loops then pause itself based on the direction.
	SUBMENUID					: 1
	SUBMENUTYPE					: 252
	SPEED						: 0
	ACTIVE,ANIM ACTIVE			: 0,0,-1,0
	SPRITEID					: 0
	ACCELERATOR					:0
	NUMBER FRAMES				: 0
	SHARE						: -1
	SOUNDTYPE					: 0
	DESC						:
*
~
