#=========================================================================
#==	ISC Common Dialog													==
#==																		==
#==																		==
#=========================================================================
#rem..........Wager
MENUID     : 20,1
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 20
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........chip 1
	SUBMENUID  : 1
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 28
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 28
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 2
	SUBMENUID  : 2
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 29
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 29
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 3
	SUBMENUID  : 3
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 30
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 30
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 4
	SUBMENUID  : 4
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 31
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 31
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 5
	SUBMENUID  : 5
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 32
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 32
	SOUNDTYPE  : 1
	DESC       :
#rem..........Instruction Text
	SUBMENUID  : 10
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 21
	SOUNDTYPE  : 0
	DESC       :
#rem..........clear
	SUBMENUID  : 11
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 22
	ACCELERATOR:0
	DRAW TYPE  : 0,0,0xff0000
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :CLEAR
#rem..........Done
	SUBMENUID  : 12
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 25
	ACCELERATOR:0
	DRAW TYPE  : 0,0,0xff0000
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :DONE
#rem..........Left Arrow
	SUBMENUID  : 13
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 33
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :
#rem..........Right Arrow
	SUBMENUID  : 14
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 36
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :
*
#rem..........Roulette Wager
MENUID     : 21,1
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 70
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........chip 1
	SUBMENUID  : 1
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 78
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 78
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 2
	SUBMENUID  : 2
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 79
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 79
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 3
	SUBMENUID  : 3
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 80
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 80
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 4
	SUBMENUID  : 4
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 81
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 81
	SOUNDTYPE  : 1
	DESC       :
#rem..........chip 5
	SUBMENUID  : 5
	SUBMENUTYPE: 39
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 82
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 82
	SOUNDTYPE  : 1
	DESC       :
#rem..........Instruction Text
	SUBMENUID  : 10
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 71
	SOUNDTYPE  : 0
	DESC       :
#rem..........clear
	SUBMENUID  : 11
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 72
	ACCELERATOR:0
	DRAW TYPE  : 0,0,0xff0000
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :CLEAR
#rem..........Done
	SUBMENUID  : 12
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 75
	ACCELERATOR:0
	DRAW TYPE  : 0,0,0xff0000
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :DONE
#rem..........Left Arrow
	SUBMENUID  : 13
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 83
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :
#rem..........Right Arrow
	SUBMENUID  : 14
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 86
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 1
	DESC       :
*
#rem..........ABOUT
MENUID     : 1000,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1600
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Text Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1601
	SOUNDTYPE  : 0
	DESC       :
#rem..........Text Line 2
	SUBMENUID  : 2
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1602
	SOUNDTYPE  : 0
	DESC       :Copyright (c) 2001 by
#rem..........Text Line 3
	SUBMENUID  : 3
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1603
	SOUNDTYPE  : 0
	DESC       :Encore Software
#rem..........Text Line 4
	SUBMENUID  : 4
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1604
	SOUNDTYPE  : 0
	DESC       :Created by ISC
#rem..........Text Line 5
	SUBMENUID  : 5
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1605
	SOUNDTYPE  : 0
	DESC       :
#rem..........Ok Button
	SUBMENUID  : 6
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1606
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........MUSIC
MENUID     : 1050,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1050
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Button 1
	SUBMENUID  : 1
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1053
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1051
	SOUNDTYPE  : 12
	DESC       :On
#rem..........Button 2
	SUBMENUID  : 2
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1053
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1052
	SOUNDTYPE  : 12
	DESC       :Off
#rem..........TITLE
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1055
	SOUNDTYPE  : 0
	DESC       :MUSIC
#rem..........Ok Button
	SUBMENUID  : 4
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1073
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
#rem..........Song 1 Checkbox
	SUBMENUID  : 5
	SUBMENUTYPE: 91
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1058
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1056
	SOUNDTYPE  : 0
	DESC       :Song Number 1
#rem..........Song 2 Checkbox
	SUBMENUID  : 6
	SUBMENUTYPE: 91
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1061
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1059
	SOUNDTYPE  : 0
	DESC       :Song Number 2
#rem..........Song 3 Checkbox
	SUBMENUID  : 7
	SUBMENUTYPE: 91
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1064
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1062
	SOUNDTYPE  : 0
	DESC       :Song Number 3
#rem..........Song 4 Checkbox
	SUBMENUID  : 8
	SUBMENUTYPE: 91
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1067
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1065
	SOUNDTYPE  : 0
	DESC       :Song Number 4
#rem..........Song 5 Checkbox
	SUBMENUID  : 9
	SUBMENUTYPE: 91
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1070
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1068
	SOUNDTYPE  : 0
	DESC       :Song Number 5
#rem..........VOLUME SLIDER
	SUBMENUID  : 10
	SUBMENUTYPE: 230
		FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1072
	ACCELERATOR: 0
	DRAW TYPE  : 20
	SHARE      : 1071
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........SOUND
MENUID     : 1100,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1100
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Button 1
	SUBMENUID  : 1
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1103
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1101
	SOUNDTYPE  : 12
	DESC       :On
#rem..........Button 2
	SUBMENUID  : 2
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1103
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1102
	SOUNDTYPE  : 12
	DESC       :Off
#rem..........TITLE
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1105
	SOUNDTYPE  : 12
	DESC       :SOUND
#rem..........Ambiance Volume
	SUBMENUID  : 4
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1106
	SOUNDTYPE  : 0
	DESC       :Ambiance Volume
#rem..........Sound Volume
	SUBMENUID  : 5
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1107
	SOUNDTYPE  : 0
	DESC       :Sound Effects Volume
#rem..........Sound Effect Volume Slider
	SUBMENUID  : 6
	SUBMENUTYPE: 230
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1110
	ACCELERATOR: 0
	DRAW TYPE  : 20
	SHARE      : 1108
	SOUNDTYPE  : 0
	DESC       :
#rem..........Ambiance Volume Slider
	SUBMENUID  : 7
	SUBMENUTYPE: 230
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1110
	ACCELERATOR: 0
	DRAW TYPE  : 20
	SHARE      : 1109
	SOUNDTYPE  : 0
	DESC       :
#rem..........Ok Button
	SUBMENUID  : 8
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1111
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........ANIMATION
MENUID     : 1150,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1150
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Button 1
	SUBMENUID  : 1
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1153
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1151
	SOUNDTYPE  : 12
	DESC       :On
#rem..........Button 2
	SUBMENUID  : 2
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1153
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1152
	SOUNDTYPE  : 12
	DESC       :Off
#rem..........TITLE
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1155
	SOUNDTYPE  : 0
	DESC       :ANIMATIONS
#rem..........Ok Button
	SUBMENUID  : 4
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1156
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........AI
MENUID     : 1151,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1150
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Button 1
	SUBMENUID  : 1
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1153
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1151
	SOUNDTYPE  : 12
	DESC       :On
#rem..........Button 2
	SUBMENUID  : 2
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1153
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1152
	SOUNDTYPE  : 12
	DESC       :Off
#rem..........TITLE
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1155
	SOUNDTYPE  : 0
	DESC       :AI CHARACTERS
#rem..........Ok Button
	SUBMENUID  : 4
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1156
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........SCREEN SIZE
MENUID     : 1152,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1150
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Button 1
	SUBMENUID  : 1
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1153
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1151
	SOUNDTYPE  : 12
	DESC       :FULL
#rem..........Button 2
	SUBMENUID  : 2
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1153
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1152
	SOUNDTYPE  : 12
	DESC       :WINDOW
#rem..........TITLE
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1155
	SOUNDTYPE  : 0
	DESC       :SCREEN SIZE
#rem..........Ok Button
	SUBMENUID  : 4
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1156
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........SPEED
MENUID     : 1200,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1200
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Button 1
	SUBMENUID  : 1
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1204
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1201
	SOUNDTYPE  : 12
	DESC       :Normal
#rem..........Button 2
	SUBMENUID  : 2
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1204
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1202
	SOUNDTYPE  : 12
	DESC       :Fast
#rem..........Button 3
	SUBMENUID  : 3
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1204
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1203
	SOUNDTYPE  : 12
	DESC       :Instant
#rem..........TITLE
	SUBMENUID  : 4
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1206
	SOUNDTYPE  : 0
	DESC       :SPEED
#rem..........Ok Button
	SUBMENUID  : 5
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1207
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........STATISTICS
MENUID     : 1500,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1500
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........List Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1501
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 2
	SUBMENUID  : 2
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1502
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 3
	SUBMENUID  : 3
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1503
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 4
	SUBMENUID  : 4
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1504
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 5
	SUBMENUID  : 5
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1505
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 6
	SUBMENUID  : 6
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1506
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 7
	SUBMENUID  : 7
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1507
	SOUNDTYPE  : 0
	DESC       :
#rem..........SCROLL UP BUTTON
	SUBMENUID  : 17
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1508
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL DOWN BUTTON
	SUBMENUID  : 18
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1511
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL THUMB
	SUBMENUID  : 19
	SUBMENUTYPE: 45,17,18,7
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1515
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 1514
	SOUNDTYPE  : 0
	DESC       :
#rem..........TITLE	
	SUBMENUID  : 20
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1516
	SOUNDTYPE  : 0
	DESC       :STATISTICS
#rem..........Starting Bank
	SUBMENUID  : 21
	SUBMENUTYPE: 60
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1517
	SOUNDTYPE  : 0
	DESC       :
#rem..........Current Bank
	SUBMENUID  : 22
	SUBMENUTYPE: 60
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1518
	SOUNDTYPE  : 0
	DESC       :
#rem..........Net Change
	SUBMENUID  : 23
	SUBMENUTYPE: 60
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1519
	SOUNDTYPE  : 0
	DESC       :
#rem..........Ok Button
	SUBMENUID  : 25
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1520
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
#rem..........Reset Button
	SUBMENUID  : 26
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1523
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :Reset
*
#rem..........INFO
MENUID     : 1450,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1450
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........List Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1451
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 2
	SUBMENUID  : 2
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1452
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 3
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1453
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 4
	SUBMENUID  : 4
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1454
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 5
	SUBMENUID  : 5
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1455
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 6
	SUBMENUID  : 6
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1456
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 7
	SUBMENUID  : 7
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1457
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 8
	SUBMENUID  : 8
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1458
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 9
	SUBMENUID  : 9
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1459
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 10
	SUBMENUID  : 10
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1460
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 11
	SUBMENUID  : 11
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1461
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 12
	SUBMENUID  : 12
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1462
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 13
	SUBMENUID  : 13
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1463
	SOUNDTYPE  : 0
	DESC       :
#rem..........SCROLL UP BUTTON
	SUBMENUID  : 17
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1464
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL DOWN BUTTON
	SUBMENUID  : 18
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1467
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL THUMB
	SUBMENUID  : 19
	SUBMENUTYPE: 45,17,18,13
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1471
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 1470
	SOUNDTYPE  : 0
	DESC       :
#rem..........TITLE	
	SUBMENUID  : 20
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1472
	SOUNDTYPE  : 0
	DESC       :INFO
#rem..........Ok Button
	SUBMENUID  : 21
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1473
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........PULL DOWN MENU
MENUID     : 1350,1
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : 1350
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Game Menu
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1351
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xfffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Options Menu
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1354
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Help Menu
	SUBMENUID  : 3
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1357
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
*
#rem..........GAME PULL DOWN MENU
MENUID     : 1370,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1370
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Game Menu
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1371
	ACCELERATOR: 0
	DRAW TYPE  : 0,251
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Options Menu
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1374
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Help Menu
	SUBMENUID  : 3
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1377
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Statistics Menu
	SUBMENUID  : 4
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1380
	SOUNDTYPE  : 12 
	DESC       :Statistics
#rem..........Leave Table
	SUBMENUID  : 5
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1381
	SOUNDTYPE  : 12 
	DESC       :Leave Table
#rem..........Exit Menu
	SUBMENUID  : 6
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1382
	SOUNDTYPE  : 12 
	DESC       :Exit
*
#rem..........OPTIONS PULL DOWN MENU
MENUID     : 1390,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1390
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Game Menu
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1391
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Options Menu
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1394
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Help Menu
	SUBMENUID  : 3
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1397
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Sound Menu
	SUBMENUID  : 4
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1400
	SOUNDTYPE  : 12 
	DESC       :Sound
#rem..........Animation Menu
	SUBMENUID  : 5
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1401
	SOUNDTYPE  : 12 
	DESC       :Animation
#rem..........Skins Menu
	SUBMENUID  : 6
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1402
	SOUNDTYPE  : 12 
	DESC       :Skins
#rem..........AI Menu
	SUBMENUID  : 7
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1403
	SOUNDTYPE  : 12 
	DESC       :AI
#rem..........ScreenSize Menu
	SUBMENUID  : 8
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1404
	SOUNDTYPE  : 12 
	DESC       :Screen Size
*
#rem..........HELP PULL DOWN MENU
MENUID     : 1410,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1410
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Game Menu
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1411
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Options Menu
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1414
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........Help Menu
	SUBMENUID  : 3
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1417
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........How To Play Menu
	SUBMENUID  : 4
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1420
	SOUNDTYPE  : 12 
	DESC       :How To Play
##rem..........Customer Service Menu
#	SUBMENUID  : 5
#	SUBMENUTYPE: 90
#	FONTTYPE   : 5
#	ACTIVE     : 1
#	SPRITEID   : -1
#	ACCELERATOR: 0
#	DRAW TYPE  : 0,0xffffff,0xffff00
#	SHARE      : 1421
#	SOUNDTYPE  : 12 
#	DESC       :Cust.Service
#rem..........About Menu
	SUBMENUID  : 6
	SUBMENUTYPE: 90
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : 1421
	SOUNDTYPE  : 12 
	DESC       :About
*
#rem..........QUIT
MENUID     : 1250,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1250
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Yes Button
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1255
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :YES
#rem..........NO Button
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1252
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :NO
#rem..........question
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1251
	SOUNDTYPE  : 0
	DESC       :Are you sure
#rem..........question
	SUBMENUID  : 4
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1258
	SOUNDTYPE  : 0
	DESC       :you want to
#rem..........question
	SUBMENUID  : 5
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1259
	SOUNDTYPE  : 0
	DESC       :exit this game?
#rem..........question
	SUBMENUID  : 6
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1260
	SOUNDTYPE  : 0
	DESC       :(Any open bets will be lost)
*
#rem..........LEAVE TABLE
MENUID     : 1251,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1250
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Yes Button
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1255
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :YES
#rem..........NO Button
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1252
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :NO
#rem..........question
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1251
	SOUNDTYPE  : 0
	DESC       :Are you sure
#rem..........question
	SUBMENUID  : 4
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1258
	SOUNDTYPE  : 0
	DESC       :you want to
#rem..........question
	SUBMENUID  : 5
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1259
	SOUNDTYPE  : 0
	DESC       :leave this table?
#rem..........question
	SUBMENUID  : 6
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1260
	SOUNDTYPE  : 0
	DESC       :(Any open bets will be lost)
*
#rem..........VerifyReset
MENUID     : 1252,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1250
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Yes Button
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1255
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :YES
#rem..........NO Button
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1252
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :NO
#rem..........question
	SUBMENUID  : 3
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1251
	SOUNDTYPE  : 0
	DESC       :Are you sure
#rem..........question
	SUBMENUID  : 4
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1258
	SOUNDTYPE  : 0
	DESC       :you want to
#rem..........question
	SUBMENUID  : 5
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1259
	SOUNDTYPE  : 0
	DESC       :reset the
#rem..........question
	SUBMENUID  : 6
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1260
	SOUNDTYPE  : 0
	DESC       :statistics?
*
#rem..........PRINT
MENUID     : 1550,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1550
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........TITLE
	SUBMENUID  : 1
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1551
	SOUNDTYPE  : 0
	DESC       :PRINT
#rem..........Ok Button
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1558
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :OK
#rem..........Send To Screen
	SUBMENUID  : 3
	SUBMENUTYPE: 91
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1554
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1552
	SOUNDTYPE  : 0
	DESC       :Send To File
#rem..........Send To Printer
	SUBMENUID  : 4
	SUBMENUTYPE: 91
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1557
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1555
	SOUNDTYPE  : 0
	DESC       :Send To Printer
*
#rem..........HOW TO PLAY (HELP)
MENUID     : 1300,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1300
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........LINE 1
	SUBMENUID  : 1
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1302
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 2
	SUBMENUID  : 2
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1303
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 3
	SUBMENUID  : 3
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1304
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 4
	SUBMENUID  : 4
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1305
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 5
	SUBMENUID  : 5
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1306
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 6
	SUBMENUID  : 6
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1307
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 7
	SUBMENUID  : 7
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1308
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 8
	SUBMENUID  : 8
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1309
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 9
	SUBMENUID  : 9
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1310
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 10
	SUBMENUID  : 10
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1311
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 11
	SUBMENUID  : 11
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1312
	SOUNDTYPE  : 0
	DESC       :
#rem..........SCROLL UP BUTTON
	SUBMENUID  : 20
	SUBMENUTYPE: 400,20,21,11
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1313
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........SCROLL DOWN BUTTON
	SUBMENUID  : 21
	SUBMENUTYPE: 405,20,21,11
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1316
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12 
	DESC       :
#rem..........SCROLL THUMB
	SUBMENUID  : 22
	SUBMENUTYPE: 45,20,21,11
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1320
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 1319
	SOUNDTYPE  : 0
	DESC       :
#rem..........TITLE
	SUBMENUID  : 23
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1301
	SOUNDTYPE  : 0
	DESC       :HELP
#rem..........Ok Button
	SUBMENUID  : 24
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1321
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........SUPPORT
MENUID     : 1600,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1600
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Text Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1601
	SOUNDTYPE  : 0
	DESC       :For Customer Support
#rem..........Text Line 2
	SUBMENUID  : 2
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1602
	SOUNDTYPE  : 0
	DESC       :Go To
#rem..........Text Line 3
	SUBMENUID  : 3
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1603
	SOUNDTYPE  : 0
	DESC       :www.encoresoftware.com/support
#rem..........Text Line 4
	SUBMENUID  : 4
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1604
	SOUNDTYPE  : 0
	DESC       :Or Telephone
#rem..........Text Line 5
	SUBMENUID  : 5
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1605
	SOUNDTYPE  : 0
	DESC       :310-719-2890 M-F 8am-5pm PST
#rem..........Ok Button
	SUBMENUID  : 6
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1606
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........Chat: Incoming Messages
MENUID     : 814,1
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........LINE 1
	SUBMENUID  : 1
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 814
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 2
	SUBMENUID  : 2
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 815
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 3
	SUBMENUID  : 3
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 816
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 4
	SUBMENUID  : 4
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 817
	SOUNDTYPE  : 0
	DESC       :
#rem..........SCROLL UP BUTTON
	SUBMENUID  : 20
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 818
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL DOWN BUTTON
	SUBMENUID  : 21
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 821
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL THUMB
	SUBMENUID  : 22
	SUBMENUTYPE: 45,20,21,4
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 825
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 824
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........Chat: Enum Player List
MENUID     : 826,1
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........LINE 1
	SUBMENUID  : 1
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 826
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 2
	SUBMENUID  : 2
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 827
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 3
	SUBMENUID  : 3
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 828
	SOUNDTYPE  : 0
	DESC       :
#rem..........LINE 4
	SUBMENUID  : 4
	SUBMENUTYPE: 41
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 829
	SOUNDTYPE  : 0
	DESC       :
#rem..........SCROLL UP BUTTON
	SUBMENUID  : 20
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 830
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL DOWN BUTTON
	SUBMENUID  : 21
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 833
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL THUMB
	SUBMENUID  : 22
	SUBMENUTYPE: 45,20,21,4
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 837
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 836
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........Chat: All Other
MENUID     : 800,1
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : -1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Input Line
	SUBMENUID  : 5
	SUBMENUTYPE: 500 
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : 813 
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 813
	SOUNDTYPE  : 12
	DESC       : 
#rem..........Quik Chat
	SUBMENUID  : 1
	SUBMENUTYPE: 50
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 801
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........Quik Sound
	SUBMENUID  : 2
	SUBMENUTYPE: 50
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 804
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........Clear Message
	SUBMENUID  : 3
	SUBMENUTYPE: 50
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 807
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........Send Message
	SUBMENUID  : 4
	SUBMENUTYPE: 50 
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 810
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........Invite Broadcast
	SUBMENUID  : 6
	SUBMENUTYPE: 50 
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1697
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
*
#rem..........QUIK CHAT
MENUID     : 1650,1
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1650
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Picture 0
	SUBMENUID  : 1651
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1651
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 1
	SUBMENUID  : 1652
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1652
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 2
	SUBMENUID  : 1653
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1653
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 3
	SUBMENUID  : 1654
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1654
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 4
	SUBMENUID  : 1655
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1655
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 5
	SUBMENUID  : 1656
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1656
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 6
	SUBMENUID  : 1657
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1657
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 7
	SUBMENUID  : 1658
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1658
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 8
	SUBMENUID  : 1659
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1660
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1659
	SOUNDTYPE  : 12
	DESC       :
#rem...........Instruction
	SUBMENUID  : 1662
	SUBMENUTYPE: 60
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1662
	SOUNDTYPE  : 12
	DESC       :Select the type of message to send.
#rem..........Cancel Button
	SUBMENUID  : 1663
	SUBMENUTYPE: 50
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1663
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........OK Button
	SUBMENUID  : 1666
	SUBMENUTYPE: 50
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1666
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
*
#rem..........QUIK SOUND
MENUID     : 1675,1
MENUTYPE   : 3
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1675
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Picture 0
	SUBMENUID  : 1676
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1676
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 1
	SUBMENUID  : 1677
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1677
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 2
	SUBMENUID  : 1678
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1678
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 3
	SUBMENUID  : 1679
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1679
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 4
	SUBMENUID  : 1680
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1680
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 5
	SUBMENUID  : 1681
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1681
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 6
	SUBMENUID  : 1682
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1682
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 7
	SUBMENUID  : 1683
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1683
	SOUNDTYPE  : 12
	DESC       :
#rem..........Picture 8
	SUBMENUID  : 1684
	SUBMENUTYPE: 110
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1685
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1684
	SOUNDTYPE  : 12
	DESC       :
#rem...........Instruction
	SUBMENUID  : 1687
	SUBMENUTYPE: 60
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1687
	SOUNDTYPE  : 0
	DESC       :Select the type of sound to send.
#rem..........Cancel Button
	SUBMENUID  : 1688
	SUBMENUTYPE: 50
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1688
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........OK Button
	SUBMENUID  : 1691
	SUBMENUTYPE: 50
	FONTTYPE   : 1
	ACTIVE     : 1
	SPRITEID   : 1691
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
*
#rem..........Timer ProgressBar
MENUID     : 1730,1
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : 1730
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 233
	FONTTYPE   : 3
	ACTIVE     : 1
	SPRITEID   : 1732
	ACCELERATOR: 0
	DRAW TYPE  : 0
	SHARE      : 1731
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........PrettyStandardPiping ( just eye candy for most offline table games)
MENUID     : 10020,1
MENUTYPE   : 13
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : 1
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 31
	FONTTYPE   : 5
	ACTIVE     : 0
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 1
	SHARE      : 1
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........PrettyRoulettePiping ( just eye candy for offline roulette games )
MENUID     : 10021,1
MENUTYPE   : 13
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : 2
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 31
	FONTTYPE   : 5
	ACTIVE     : 0
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 1
	SHARE      : 2
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........PrettyPokerPiping ( just eye candy for offline poker games )
MENUID     : 10022,1
MENUTYPE   : 13
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : 3
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 31
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 1
	SHARE      : 3
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........PrettyPokerPiping ( just eye candy for online games with chat )
MENUID     : 10023,1
MENUTYPE   : 13
MOVEABLE   : 0
ACTIVE     : 1
SPRITEID   : 4
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 31
	FONTTYPE   : 5
	ACTIVE     : 0
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 1
	SHARE      : 4
	SOUNDTYPE  : 0
	DESC       :
*
#rem..........MinMax
MENUID     : 1025,1
MENUTYPE   : 1
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1025
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 0
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 1026
	SOUNDTYPE  : 0
	DESC       :Max
#rem..........Line 2
	SUBMENUID  : 2
	SUBMENUTYPE: 61
		FONTTYPE   : 5
	ACTIVE     : 0
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff
	SHARE      : 1027
	SOUNDTYPE  : 0
	DESC       :Min
#rem..........Change Button
	SUBMENUID  : 4
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 0
	SPRITEID   : 1028
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
*
#rem..........CHANGE TABLE STAKES
MENUID     : 1700,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1700
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........Button 1
	SUBMENUID  : 1
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1704
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 2
	SUBMENUID  : 2
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1705
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 3
	SUBMENUID  : 3
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1706
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 4
	SUBMENUID  : 4
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1707
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 5
	SUBMENUID  : 5
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1708
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 6
	SUBMENUID  : 6
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1709
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 7
	SUBMENUID  : 7
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1710
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 8
	SUBMENUID  : 8
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1711
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 9
	SUBMENUID  : 9
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1712
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 10
	SUBMENUID  : 10
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1713
	SOUNDTYPE  : 12
	DESC       :
#rem..........Button 11
	SUBMENUID  : 11
	SUBMENUTYPE: 110
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1715
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1714
	SOUNDTYPE  : 12
	DESC       :
#rem..........TITLE
	SUBMENUID  : 12
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1701
	SOUNDTYPE  : 0
	DESC       :CHANGE TABLE STAKES
#rem..........Text Line 1
	SUBMENUID  : 13
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1702
	SOUNDTYPE  : 0
	DESC       :Choose your new
#rem..........Text Line 2
	SUBMENUID  : 14
	SUBMENUTYPE: 61
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR: 0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1703
	SOUNDTYPE  : 0
	DESC       :table stakes
#rem..........Cancel Button
	SUBMENUID  : 15
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1718
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :Cancel
#rem..........Ok Button
	SUBMENUID  : 16
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1721
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
#rem..........SKIN CHANGE
MENUID     : 1750,1
MENUTYPE   : 8
MOVEABLE   : 0
ACTIVE     : 0
SPRITEID   : 1750
ACCELERATOR: 0
DRAW TYPE  : 0
SHARE      : 0
X-CORD     : -1
Y-CORD     : -1
DESC       :
#rem..........List Line 1
	SUBMENUID  : 1
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1751
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 2
	SUBMENUID  : 2
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1752
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 3
	SUBMENUID  : 3
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1753
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 4
	SUBMENUID  : 4
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1754
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 5
	SUBMENUID  : 5
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1755
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 6
	SUBMENUID  : 6
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1756
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 7
	SUBMENUID  : 7
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1757
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 8
	SUBMENUID  : 8
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1758
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 9
	SUBMENUID  : 9
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1759
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 10
	SUBMENUID  : 10
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1760
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 11
	SUBMENUID  : 11
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1761
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 12
	SUBMENUID  : 12
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1762
	SOUNDTYPE  : 0
	DESC       :
#rem..........List Line 13
	SUBMENUID  : 13
	SUBMENUTYPE: 41
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1763
	SOUNDTYPE  : 0
	DESC       :
#rem..........SCROLL UP BUTTON
	SUBMENUID  : 20
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1764
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL DOWN BUTTON
	SUBMENUID  : 21
	SUBMENUTYPE: 3
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1767
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :
#rem..........SCROLL THUMB
	SUBMENUID  : 22
	SUBMENUTYPE: 45,20,21,7
	FONTTYPE   : 0
	ACTIVE     : 1
	SPRITEID   : 1771
	ACCELERATOR:0
	DRAW TYPE  : 0
	SHARE      : 1770
	SOUNDTYPE  : 0
	DESC       :
#rem..........TITLE	
	SUBMENUID  : 23
	SUBMENUTYPE: 60
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : -1
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,-1,-1,0
	SHARE      : 1772
	SOUNDTYPE  : 0
	DESC       :SKIN CHANGE
#rem..........Cancel Button
	SUBMENUID  : 24
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1773
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :Cancel
#rem..........Ok Button
	SUBMENUID  : 25
	SUBMENUTYPE: 50
	FONTTYPE   : 5
	ACTIVE     : 1
	SPRITEID   : 1776
	ACCELERATOR:0
	DRAW TYPE  : 0,0xffffff,0xffff00
	SHARE      : -1
	SOUNDTYPE  : 12
	DESC       :OK
*
~

